language: ruby
env: RACK_ENV=development
sudo: false
rvm:
- 2.6.3
before_install:
- gem install -v 2.0.2 bundler
deploy:
  provider: rubygems
  api_key:
    secure: D6gxKHMdsxvoTQ7/DmmqcY6MIyx8LVevgyG9MJg0VonRrfv8G0NDFWHGd01QVogos8qZ1Jedxa86ywLsZxhEXJXZJpJbfBBRWI4bcehDutSBmfYNFUUOKV9Gc2+Pr4w4Vu4KH9mOwCWrWAtp+fprs0xmwsKHTGY1nA5824LWdBaACWZj6YYPd6ax1KgGKnxJy3JdWbzChMWjiJfkQQGmWuuoDHmxKFcJ4voLWFWG6whboWsa0w6CYC2wOqIHO/1eOD2ir1Bayeu6maQPCadQfiTTgzYGttk3NjFJCcNqwNVGHFM2i9NAoXCkO4MsGGgf91Jk3YlwMmg0wYMiWRQotb9rWB2qxIHWn+iwU7nprnelVu2NPFhbZz33gAWZPXa7xIrjhhzVhPBiRM58d7PgAb3gNTXZM1HCI3WMikzBEbQQ4hNyA41fkNNNzrbey6XyjcxtoaIe8StfNBMwEYfZl2F8WMzkPYq6kshFu0zYzLdYv/XXpCUcZG10aWvB/c55M7GT+Pb70WUKFQHV54B/cfWmOxs/hv97MPcGBb7jOqFtSZy8psQ/8rrMqMCZCMDljz7R7xL/igXg8QBhLyRilS9jL6Oix4iaN+tpjVI+lYFpufoTCbsKpTwKx/IcYKP+FY+qIO8a93lGmHHleRoLfjjDhOeBYdB7Wg1uFPQCrOs=
  gem: mumuki-puzzle-runner
  on:
    tags: true
    repo: mumuki/mumuki-puzzle-runner
  skip_cleanup: 'true'
